#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Feb 08, 2019 01:54:38 PM IST  platform: Windows NT

import sys
import codecs
try:
    from tkinter import filedialog
    import Tkinter as tk
    import re
    import string
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pratick_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    pratick_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    pratick_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None




class Toplevel1:

    def decryptr(self):

        cipher = self.Entry3.get()
        key = self.Entry6.get()
        if(int(key)==1):
            self.Label6["text"] = cipher
        else:
            rail = [['\n' for i in range(len(cipher))]
                    for j in range(int(key))]

            # to find the direction
            dir_down = None
            row, col = 0, 0

            # mark the places with '*'
            for i in range(len(cipher)):
                if row == 0:
                    dir_down = True
                if row == int(key) - 1:
                    dir_down = False

                # place the marker
                rail[row][col] = '*'
                col += 1

                # find the next row
                # using direction flag
                if dir_down:
                    row += 1
                else:
                    row -= 1

            # now we can construct the
            # fill the rail matrix
            index = 0
            for i in range(int(key)):
                for j in range(len(cipher)):
                    if ((rail[i][j] == '*') and
                            (index < len(cipher))):
                        rail[i][j] = cipher[index]
                        index += 1

            result = []
            row, col = 0, 0
            for i in range(len(cipher)):

                # check the direction of flow
                if row == 0:
                    dir_down = True
                if row == int(key) - 1:
                    dir_down = False

                # place the marker
                if (rail[row][col] != '*'):
                    result.append(rail[row][col])
                    col += 1

                # find the next row using
                # direction flag
                if dir_down:
                    row += 1
                else:
                    row -= 1
            self.Label6["text"] = ("".join(result))

    def encryptr(self):
        text = self.Entry3.get()
        key = self.Entry6.get()
        if(int(key)==1):
            self.Label6["text"] =text

        else:
            rail = [['\n' for i in range(len(text))]
                    for j in range(int(key))]
            # to find the direction
            dir_down = False
            row, col = 0, 0

            for i in range(len(text)):

                if (row == 0) or (row == int(key) - 1):
                    dir_down = not dir_down

                # fill the corresponding alphabet
                rail[row][col] = text[i]
                col += 1

                # find the next row using
                # direction flag
                if dir_down:
                    row += 1
                else:
                    row -= 1

            result = []
            for i in range(int(key)):
                for j in range(len(text)):
                    if rail[i][j] != '\n':
                        result.append(rail[i][j])
            # self.Label6["text"] = result
            self.Label6["text"] = ("".join(result))

    def decryptv(self):
        alphabets = "abcdefghijklmnopqrstuvwxyz"
        p = ""
        c = self.Entry1.get()
        k = self.Entry9.get()
        kpos = []
        for x in k:
            kpos.append(alphabets.find(x))
        i = 0
        for x in c:
            if i == len(kpos):
                i = 0
            pos = alphabets.find(x.lower()) - kpos[i]
            if pos < 0:
                pos = pos + 26
            p += alphabets[pos].lower()
            i += 1
        self.Label6["text"] = p

    def encryptv(self):
        alphabets = "abcdefghijklmnopqrstuvwxyz"
        p = self.Entry1.get()
        k = self.Entry9.get()
        c = ""
        kpos = []  # return the index of characters ex: if k='d' then kpos= 3
        for x in k:
            # kpos += alphabets.find(x) #change the int value to string
            kpos.append(alphabets.find(x))
        i = 0
        for x in p:
            if i == len(kpos):
                i = 0
            pos = alphabets.find(x) + kpos[i]  # find the number or index of the character and perform the shift with the key
            print(pos)
            if pos > 25:
                pos = pos - 26  # check you exceed the limit
            c += alphabets[pos].capitalize()  # because the cipher text always capital letters
            i += 1
        self.Label6["text"] = c

    def delete(self):
        self.Entry2.delete(first=0, last=100)
        self.Entry4.delete(first=0, last=100)
        self.Entry3.delete(first=0, last=100)
        self.Entry6.delete(first=0, last=100)
        self.Entry1.delete(first=0, last=100)
        self.Entry9.delete(first=0, last=100)
        self.Entry7.delete(first=0, last=100)
        self.Entry8.delete(first=0, last=100)
        self.Label6["text"] = ' '
        self.Label12["text"] = ' '

    def browse(self):

        root.filename = filedialog.askopenfilename(initialdir="/", title="Select file", filetypes=(("jpeg files", "*.jpg"), ("all files", "*.*")))
        print(root.filename)

    def deffi(self):

        p = 353
        a = self.Entry7.get()
        B = self.Entry8.get()
        result = (int(B) ** int(a)) % p
        result = result % 26
        self.Label12["text"] = result

    def encryptc(self):
        text = self.Entry2.get()
        s = self.Entry4.get()
        result = ""
        # traverse text
        for i in range(len(text)):
            char = text[i]
            if(char==" "):
                result +=' '
            else:
                # Encrypt uppercase characters
                if (char.isupper()):
                    result += chr((ord(char) + int(s)+4 - 65) % 26 + 65)

                    # Encrypt lowercase characters
                else:
                    result += chr((ord(char) + int(s)+4 - 97) % 26 + 97)


        self.Label6["text"]=result

    def decryptc(self):
        """Decrypt the string and return the plaintext"""
        key = 'abcdefghijklmnopqrstuvwxyz'
        result = ''
        text = self.Entry2.get()
        s = self.Entry4.get()
        for l in text:
            try:
                if (l==' '):
                    result += ' '

                else:
                    i = (key.index(l) - int(s)-4) % 26
                    result += key[i]
            except ValueError:
                result += l
        self.Label6["text"] = result
    def __init__(self, top=None):

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 13 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI} -size 23 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font14 = "-family {Segoe UI} -size 17 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("1176x919+308+37")
        top.title("Ecrypt Stream Cipher")
        top.configure(background="#2b798c")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.034, rely=0.022, relheight=0.354
                , relwidth=0.276)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#2b798c")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=325)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.277, rely=0.062, height=56, width=142)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#2b798c")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Caesar Cipher''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.092, rely=0.8, height=33, width=82)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Encryption''')
        self.Button1.configure(command=self.encryptc)


        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.615, rely=0.8, height=33, width=85)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Decryption''')
        self.Button2.configure(command=self.decryptc)

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.277, rely=0.369,height=24, relwidth=0.628)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Entry4 = tk.Entry(self.Frame1)
        self.Entry4.place(relx=0.277, rely=0.585,height=24, relwidth=0.628)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font=font10)
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")
        self.Entry4.configure(show="*")

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.031, rely=0.369, height=26, width=74)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#2b798c")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Text''')

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.092, rely=0.585, height=26, width=30)
        self.Label7.configure(activebackground="#2b798c")
        self.Label7.configure(activeforeground="white")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#2b798c")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Key''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.689, rely=0.022, relheight=0.452
                , relwidth=0.293)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(background="#2b798c")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=345)

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.203, rely=0.048, height=56, width=182)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#2b798c")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Vigenere Cipher''')

        self.Entry1 = tk.Entry(self.Frame2)
        self.Entry1.place(relx=0.319, rely=0.289,height=24, relwidth=0.591)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Button3 = tk.Button(self.Frame2)
        self.Button3.place(relx=0.174, rely=0.651, height=33, width=82)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Encryption''')
        self.Button3.configure(command=self.encryptv)

        self.Button4 = tk.Button(self.Frame2)
        self.Button4.place(relx=0.638, rely=0.651, height=33, width=85)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Decryption''')
        self.Button4.configure(command=self.decryptv)

        self.Entry9 = tk.Entry(self.Frame2)
        self.Entry9.place(relx=0.319, rely=0.458,height=24, relwidth=0.591)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font=font10)
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(highlightbackground="#d9d9d9")
        self.Entry9.configure(highlightcolor="black")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(selectbackground="#c4c4c4")
        self.Entry9.configure(selectforeground="black")

        self.Label17 = tk.Label(self.Frame2)
        self.Label17.place(relx=0.087, rely=0.289, height=26, width=52)
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(background="#2b798c")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#000000")
        self.Label17.configure(highlightbackground="#d9d9d9")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''Text''')

        self.Label18 = tk.Label(self.Frame2)
        self.Label18.place(relx=0.087, rely=0.458, height=26, width=52)
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(activeforeground="black")
        self.Label18.configure(background="#2b798c")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(foreground="#000000")
        self.Label18.configure(highlightbackground="#d9d9d9")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text='''Key''')

        self.Button7 = tk.Button(self.Frame2)
        self.Button7.place(relx=0.377, rely=0.843, height=43, width=116)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''Browse''')
        self.Button7.configure(command=self.browse)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.034, rely=0.511, relheight=0.365
                , relwidth=0.276)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(background="#2b798c")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")
        self.Frame3.configure(width=325)

        self.Label3 = tk.Label(self.Frame3)
        self.Label3.place(relx=0.246, rely=0.06, height=56, width=180)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#2b798c")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Rail Fence Cipher''')

        self.Entry3 = tk.Entry(self.Frame3)
        self.Entry3.place(relx=0.308, rely=0.388,height=24, relwidth=0.628)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Button5 = tk.Button(self.Frame3)
        self.Button5.place(relx=0.123, rely=0.806, height=33, width=82)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Encryption''')
        self.Button5.configure(command=self.encryptr)

        self.Button6 = tk.Button(self.Frame3)
        self.Button6.place(relx=0.615, rely=0.806, height=33, width=85)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Decryption''')
        self.Button6.configure(command=self.decryptr)

        self.Entry6 = tk.Entry(self.Frame3)
        self.Entry6.place(relx=0.308, rely=0.567,height=24, relwidth=0.628)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font=font10)
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(show="*")

        self.Label8 = tk.Label(self.Frame3)
        self.Label8.place(relx=0.123, rely=0.388, height=26, width=34)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#2b798c")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Text''')

        self.Label9 = tk.Label(self.Frame3)
        self.Label9.place(relx=0.123, rely=0.567, height=26, width=30)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#2b798c")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Key''')

        self.Button12 = tk.Button(top)
        self.Button12.place(relx=0.544, rely=0.751, height=43, width=116)
        self.Button12.configure(activebackground="#ececec")
        self.Button12.configure(activeforeground="#000000")
        self.Button12.configure(background="#d9d9d9")
        self.Button12.configure(disabledforeground="#a3a3a3")
        self.Button12.configure(foreground="#000000")
        self.Button12.configure(highlightbackground="#d9d9d9")
        self.Button12.configure(highlightcolor="black")
        self.Button12.configure(pady="0")
        self.Button12.configure(text='''EXIT''')
        self.Button12.configure(command=root.destroy)

        self.Button13 = tk.Button(top)
        self.Button13.place(relx=0.391, rely=0.751, height=43, width=106)
        self.Button13.configure(activebackground="#ececec")
        self.Button13.configure(activeforeground="#000000")
        self.Button13.configure(background="#d9d9d9")
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="black")
        self.Button13.configure(pady="0")
        self.Button13.configure(text='''RESET''')
        self.Button13.configure(command=self.delete)

        self.Frame4 = tk.Frame(top)
        self.Frame4.place(relx=0.689, rely=0.522, relheight=0.365
                , relwidth=0.285)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(background="#2b798c")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")
        self.Frame4.configure(width=335)

        self.Label10 = tk.Label(self.Frame4)
        self.Label10.place(relx=0.06, rely=0.299, height=26, width=77)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#2b798c")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Private key''')

        self.Label11 = tk.Label(self.Frame4)
        self.Label11.place(relx=0.06, rely=0.507, height=26, width=72)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#2b798c")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Public key''')

        self.Entry7 = tk.Entry(self.Frame4)
        self.Entry7.place(relx=0.358, rely=0.299,height=24, relwidth=0.609)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font=font10)
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        self.Entry7.configure(show="*")

        self.Entry8 = tk.Entry(self.Frame4)
        self.Entry8.place(relx=0.358, rely=0.507,height=24, relwidth=0.609)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font=font10)
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")
        self.Entry8.configure(show="*")

        self.Label12 = tk.Label(self.Frame4)
        self.Label12.place(relx=0.358, rely=0.866, height=26, width=202)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#2b798c")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#35f21f",font=font11)
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(width=202)

        self.Label13 = tk.Label(self.Frame4)
        self.Label13.place(relx=0.09, rely=0.866, height=26, width=82)
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(background="#2b798c")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")
        self.Label13.configure(text='''Shared key''')

        self.Button8 = tk.Button(self.Frame4)
        self.Button8.place(relx=0.537, rely=0.687, height=33, width=81)
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Go''')
        self.Button8.configure(command=self.deffi)

        self.Label16 = tk.Label(self.Frame4)
        self.Label16.place(relx=0.179, rely=0.09, height=36, width=212)
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(background="#2b798c")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(font=font13)
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(highlightbackground="#d9d9d9")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''DHA Key Exchange''')

        self.Frame6 = tk.Frame(top)
        self.Frame6.place(relx=0.34, rely=0.185, relheight=0.343, relwidth=0.336)

        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief='groove')
        self.Frame6.configure(background="#2b798c")
        self.Frame6.configure(highlightbackground="#d9d9d9")
        self.Frame6.configure(highlightcolor="black")
        self.Frame6.configure(width=395)

        self.Label5 = tk.Label(self.Frame6)
        self.Label5.place(relx=0.025, rely=0.032, height=56, width=172)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#2b798c")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font12)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Output:-''')

        self.Label6 = tk.Label(self.Frame6)
        self.Label6.place(relx=0.127, rely=0.317, height=156, width=292)
        self.Label6.configure(background="#2b798c")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font11)
        self.Label6.configure(foreground="#35f21f")
        self.Label6.configure(width=292)

        self.Label14 = tk.Label(top)
        self.Label14.place(relx=0.06, rely=0.947, height=46, width=292)
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#2b798c")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(font=font14)
        self.Label14.configure(foreground="#35f21f")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''@powered by Krypton''')

if __name__ == '__main__':
    vp_start_gui()





